/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

 /*
 * WorkAreaJPanel.java
 *
 * Created on May 17, 2020, 8:35:29 AM
 */
package UserInterface.Main.WorkSpaceProfiles;

import TheBusiness.Business.Business;
import UserInterface.ManageTheBusiness.ManageTheBusinessJPanel;
import UserInterface.ProductManagement.ManageSuppliersJPanel;
import javax.swing.JPanel;

/**
 *
 * @author kal
 */
public class BusinessManagerWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel CardSequencePanel;
    private Business business;

    /**
     * Creates new form UnitRiskWorkArea
     */
    public BusinessManagerWorkAreaJPanel(Business b, JPanel clp) {
        this.business = b;
        this.CardSequencePanel = clp;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        manageBusiness = new javax.swing.JButton();
        manageSalesPerson = new javax.swing.JButton();
        manageSuppliers = new javax.swing.JButton();
        managePrices = new javax.swing.JButton();
        manageCustomers = new javax.swing.JButton();
        performanceReports = new javax.swing.JButton();
        Title = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(51, 51, 51));

        manageBusiness.setBackground(new java.awt.Color(102, 153, 255));
        manageBusiness.setFont(getFont());
        manageBusiness.setForeground(new java.awt.Color(255, 255, 255));
        manageBusiness.setText("Manage The Business");
        manageBusiness.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        manageBusiness.setMaximumSize(new java.awt.Dimension(200, 40));
        manageBusiness.setMinimumSize(new java.awt.Dimension(20, 23));
        manageBusiness.setOpaque(true);
        manageBusiness.setPreferredSize(new java.awt.Dimension(240, 30));
        manageBusiness.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageBusinessIdentifyResourceAssetsActionPerformed(evt);
            }
        });

        manageSalesPerson.setBackground(new java.awt.Color(102, 153, 255));
        manageSalesPerson.setFont(getFont());
        manageSalesPerson.setForeground(new java.awt.Color(255, 255, 255));
        manageSalesPerson.setText("Manage Sales Personnel");
        manageSalesPerson.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        manageSalesPerson.setMaximumSize(new java.awt.Dimension(200, 40));
        manageSalesPerson.setMinimumSize(new java.awt.Dimension(20, 20));
        manageSalesPerson.setOpaque(true);
        manageSalesPerson.setPreferredSize(new java.awt.Dimension(240, 25));
        manageSalesPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageSalesPersonActionPerformed(evt);
            }
        });

        manageSuppliers.setBackground(new java.awt.Color(102, 153, 255));
        manageSuppliers.setFont(getFont());
        manageSuppliers.setForeground(new java.awt.Color(255, 255, 255));
        manageSuppliers.setText("Manage Suppliers");
        manageSuppliers.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        manageSuppliers.setMaximumSize(new java.awt.Dimension(200, 40));
        manageSuppliers.setMinimumSize(new java.awt.Dimension(20, 20));
        manageSuppliers.setOpaque(true);
        manageSuppliers.setPreferredSize(new java.awt.Dimension(240, 25));
        manageSuppliers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageSuppliersActionPerformed(evt);
            }
        });

        managePrices.setBackground(new java.awt.Color(102, 153, 255));
        managePrices.setFont(getFont());
        managePrices.setForeground(new java.awt.Color(255, 255, 255));
        managePrices.setText("Manage Prices");
        managePrices.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        managePrices.setMaximumSize(new java.awt.Dimension(145, 40));
        managePrices.setMinimumSize(new java.awt.Dimension(20, 20));
        managePrices.setOpaque(true);
        managePrices.setPreferredSize(new java.awt.Dimension(240, 25));
        managePrices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managePricesIdentifyEventsActionPerformed(evt);
            }
        });

        manageCustomers.setBackground(new java.awt.Color(102, 153, 255));
        manageCustomers.setFont(getFont());
        manageCustomers.setForeground(new java.awt.Color(255, 255, 255));
        manageCustomers.setText("Manage Customers");
        manageCustomers.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        manageCustomers.setMaximumSize(new java.awt.Dimension(200, 40));
        manageCustomers.setMinimumSize(new java.awt.Dimension(20, 20));
        manageCustomers.setOpaque(true);
        manageCustomers.setPreferredSize(new java.awt.Dimension(240, 25));
        manageCustomers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageCustomersActionPerformed(evt);
            }
        });

        performanceReports.setBackground(new java.awt.Color(102, 153, 255));
        performanceReports.setFont(getFont());
        performanceReports.setForeground(new java.awt.Color(255, 255, 255));
        performanceReports.setText("Performance Reports");
        performanceReports.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        performanceReports.setMaximumSize(new java.awt.Dimension(200, 40));
        performanceReports.setMinimumSize(new java.awt.Dimension(20, 20));
        performanceReports.setOpaque(true);
        performanceReports.setPreferredSize(new java.awt.Dimension(240, 25));
        performanceReports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                performanceReportsActionPerformed(evt);
            }
        });

        Title.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        Title.setText("Business");

        btnLogout.setBackground(new java.awt.Color(102, 153, 255));
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setText("Logout");
        btnLogout.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnLogout.setMaximumSize(new java.awt.Dimension(200, 40));
        btnLogout.setMinimumSize(new java.awt.Dimension(20, 20));
        btnLogout.setOpaque(true);
        btnLogout.setPreferredSize(new java.awt.Dimension(240, 25));
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(manageSalesPerson, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(managePrices, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(manageBusiness, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(manageSuppliers, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(Title)))))
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(manageCustomers, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(performanceReports, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(399, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Title)
                    .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(manageBusiness, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(manageSuppliers, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(manageCustomers, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(manageSalesPerson, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(managePrices, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(performanceReports, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(206, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void manageBusinessIdentifyResourceAssetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageBusinessIdentifyResourceAssetsActionPerformed
        ManageTheBusinessJPanel panel = new ManageTheBusinessJPanel(business, CardSequencePanel);
        CardSequencePanel.add("ManageBusiness", panel);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);

    }//GEN-LAST:event_manageBusinessIdentifyResourceAssetsActionPerformed

    private void manageSalesPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageSalesPersonActionPerformed
        javax.swing.JOptionPane.showMessageDialog(this, "Sales Personnel Management not implemented yet.");
}//GEN-LAST:event_manageSalesPersonActionPerformed

    private void manageSuppliersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageSuppliersActionPerformed
        ManageSuppliersJPanel panel = new ManageSuppliersJPanel(business, CardSequencePanel);
        CardSequencePanel.add("ManageSuppliers", panel);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_manageSuppliersActionPerformed

    private void managePricesIdentifyEventsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managePricesIdentifyEventsActionPerformed
        // TODO add your handling code here:
        CardSequencePanel.removeAll();
        //    IdentifyEventTypes iet= new IdentifyEventTypes(businessunit, CardSequencePanel);

        //    CardSequencePanel.add("IdentifyEventTypes", iet);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
        //((java.awt.CardLayout)CardSequencePanel.getLayout()).show(CardSequencePanel, "IdentifyEventTypes");
}//GEN-LAST:event_managePricesIdentifyEventsActionPerformed

    private void manageCustomersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageCustomersActionPerformed
        // TODO add your handling code here:

        CardSequencePanel.removeAll();
        //      ViewBusinessUnitRiskProfile drpd= new ViewBusinessUnitRiskProfile(businessunit, CardSequencePanel);
//        ManageHazards drpd = new ManageHazards(businessunit, CardSequencePanel);
//        CardSequencePanel.add("ManageRiskProfiles", drpd);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
}//GEN-LAST:event_manageCustomersActionPerformed

    private void performanceReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_performanceReportsActionPerformed
        // TODO add your handling code here:

        CardSequencePanel.removeAll();
//        ManageIncidents aos = new  ManageIncidents(businessunit, CardSequencePanel);
        // aos.setAgenda(businessunit.getRiskManagementAgenda());
//        CardSequencePanel.add("RiskAgendaObjectives", aos);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
}//GEN-LAST:event_performanceReportsActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogoutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Title;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton manageBusiness;
    private javax.swing.JButton manageCustomers;
    private javax.swing.JButton managePrices;
    private javax.swing.JButton manageSalesPerson;
    private javax.swing.JButton manageSuppliers;
    private javax.swing.JButton performanceReports;
    // End of variables declaration//GEN-END:variables

}
