/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

 /*
 * WorkAreaJPanel.java
 *
 * Created on May 17, 2020, 8:35:29 AM
 */
package UserInterface.Main.WorkSpaceProfiles;

import MarketingManagement.MarketingPersonProfile;
import TheBusiness.Business.Business;
import UserInterface.ManageTheBusiness.ManageTheBusinessJPanel;
import UserInterface.PricingManagement.PricingManagerWorkAreaPanel;
import UserInterface.ProductManagement.ManageSuppliersJPanel;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author kal
 */
public class MarketingManagerWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel cardContainer;
    private Business business;
    private final MarketingPersonProfile mpp;

    /**
     * Creates new form UnitRiskWorkArea
     *
     * @param b
     * @param mpp
     * @param clp
     */
    public MarketingManagerWorkAreaJPanel(Business b, MarketingPersonProfile mpp, JPanel clp) {
        this.business = b;
        this.cardContainer = clp;
        this.mpp = mpp;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        manageMarkets = new javax.swing.JButton();
        manageChannels = new javax.swing.JButton();
        managePrices = new javax.swing.JButton();
        performanceReports = new javax.swing.JButton();
        Title = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(51, 51, 51));

        manageMarkets.setBackground(new java.awt.Color(102, 153, 255));
        manageMarkets.setFont(getFont());
        manageMarkets.setForeground(new java.awt.Color(255, 255, 255));
        manageMarkets.setText("Manage Markets");
        manageMarkets.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        manageMarkets.setMaximumSize(new java.awt.Dimension(200, 40));
        manageMarkets.setMinimumSize(new java.awt.Dimension(20, 23));
        manageMarkets.setOpaque(true);
        manageMarkets.setPreferredSize(new java.awt.Dimension(240, 30));
        manageMarkets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageMarketsIdentifyResourceAssetsActionPerformed(evt);
            }
        });

        manageChannels.setBackground(new java.awt.Color(102, 153, 255));
        manageChannels.setFont(getFont());
        manageChannels.setForeground(new java.awt.Color(255, 255, 255));
        manageChannels.setText("Manage Channels");
        manageChannels.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        manageChannels.setMaximumSize(new java.awt.Dimension(200, 40));
        manageChannels.setMinimumSize(new java.awt.Dimension(20, 20));
        manageChannels.setOpaque(true);
        manageChannels.setPreferredSize(new java.awt.Dimension(240, 25));
        manageChannels.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageChannelsActionPerformed(evt);
            }
        });

        managePrices.setBackground(new java.awt.Color(102, 153, 255));
        managePrices.setFont(getFont());
        managePrices.setForeground(new java.awt.Color(255, 255, 255));
        managePrices.setText("Manage Prices");
        managePrices.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        managePrices.setMaximumSize(new java.awt.Dimension(145, 40));
        managePrices.setMinimumSize(new java.awt.Dimension(20, 20));
        managePrices.setOpaque(true);
        managePrices.setPreferredSize(new java.awt.Dimension(240, 25));
        managePrices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managePricesIdentifyEventsActionPerformed(evt);
            }
        });

        performanceReports.setBackground(new java.awt.Color(102, 153, 255));
        performanceReports.setFont(getFont());
        performanceReports.setForeground(new java.awt.Color(255, 255, 255));
        performanceReports.setText("Performance Reports");
        performanceReports.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        performanceReports.setMaximumSize(new java.awt.Dimension(200, 40));
        performanceReports.setMinimumSize(new java.awt.Dimension(20, 20));
        performanceReports.setOpaque(true);
        performanceReports.setPreferredSize(new java.awt.Dimension(240, 25));
        performanceReports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                performanceReportsActionPerformed(evt);
            }
        });

        Title.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        Title.setText("Marketing ");

        btnLogout.setBackground(new java.awt.Color(102, 153, 255));
        btnLogout.setFont(getFont());
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setText("Logout");
        btnLogout.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnLogout.setMaximumSize(new java.awt.Dimension(200, 40));
        btnLogout.setMinimumSize(new java.awt.Dimension(20, 20));
        btnLogout.setOpaque(true);
        btnLogout.setPreferredSize(new java.awt.Dimension(240, 25));
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(manageMarkets, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addComponent(manageChannels, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(managePrices, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(performanceReports, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(Title)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(222, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Title)
                    .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(manageMarkets, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(manageChannels, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(managePrices, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(performanceReports, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(215, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void manageMarketsIdentifyResourceAssetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageMarketsIdentifyResourceAssetsActionPerformed
        ManageTheBusinessJPanel panel
                = new ManageTheBusinessJPanel(business, cardContainer);

        cardContainer.add("ManageMarkets", panel);
        ((CardLayout) cardContainer.getLayout()).show(cardContainer, "ManageMarkets");

    }//GEN-LAST:event_manageMarketsIdentifyResourceAssetsActionPerformed

    private void manageChannelsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageChannelsActionPerformed
        ManageSuppliersJPanel panel
                = new ManageSuppliersJPanel(business, cardContainer);

        cardContainer.add("ManageChannels", panel);
        ((CardLayout) cardContainer.getLayout()).show(cardContainer, "ManageChannels");

    }//GEN-LAST:event_manageChannelsActionPerformed

    private void managePricesIdentifyEventsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managePricesIdentifyEventsActionPerformed
        PricingManagerWorkAreaPanel panel
                = new PricingManagerWorkAreaPanel(business, cardContainer);
        
        cardContainer.add(PricingManagerWorkAreaPanel.CARD_NAME, panel);
        ((CardLayout) cardContainer.getLayout())
                .show(cardContainer, PricingManagerWorkAreaPanel.CARD_NAME);
}//GEN-LAST:event_managePricesIdentifyEventsActionPerformed

    private void performanceReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_performanceReportsActionPerformed
        javax.swing.JOptionPane.showMessageDialog(this,
                "Performance reporting coming soon.");
}//GEN-LAST:event_performanceReportsActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogoutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Title;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton manageChannels;
    private javax.swing.JButton manageMarkets;
    private javax.swing.JButton managePrices;
    private javax.swing.JButton performanceReports;
    // End of variables declaration//GEN-END:variables

}
