/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

 /*
 * WorkAreaJPanel.java
 *
 * Created on May 17, 2020, 8:35:29 AM
 */
package UserInterface.Main.WorkSpaceProfiles;

import TheBusiness.Business.Business;
import TheBusiness.CustomerManagement.CustomerProfile;
import TheBusiness.SalesManagement.SalesPersonProfile;
import UserInterface.Main.WorkSpaceProfiles.OrderManagement.ManageSalesPersonOrdersJPanel;
import UserInterface.Main.WorkSpaceProfiles.OrderManagement.ProcessOrderJPanel;
import javax.swing.JPanel;

/**
 *
 * @author kal
 */
public class SalesPersonWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel CardSequencePanel;
    private Business business;
    private SalesPersonProfile salesperson;

    /**
     * Creates new form UnitRiskWorkArea
     *
     * @param b
     * @param spp
     * @param clp
     */
    public SalesPersonWorkAreaJPanel(Business b, SalesPersonProfile spp, JPanel clp) {
        this.business = b;
        this.salesperson = spp;
        this.CardSequencePanel = clp;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        serveCustomer = new javax.swing.JButton();
        manageProfile = new javax.swing.JButton();
        reviewOrders = new javax.swing.JButton();
        viewCommission = new javax.swing.JButton();
        performanceReports = new javax.swing.JButton();
        customerNameTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Title = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(51, 51, 51));

        serveCustomer.setBackground(new java.awt.Color(102, 153, 255));
        serveCustomer.setFont(getFont());
        serveCustomer.setForeground(new java.awt.Color(255, 255, 255));
        serveCustomer.setText("Serve Customers");
        serveCustomer.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        serveCustomer.setMaximumSize(new java.awt.Dimension(200, 40));
        serveCustomer.setMinimumSize(new java.awt.Dimension(20, 23));
        serveCustomer.setOpaque(true);
        serveCustomer.setPreferredSize(new java.awt.Dimension(240, 30));
        serveCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serveCustomerIdentifyResourceAssetsActionPerformed(evt);
            }
        });

        manageProfile.setBackground(new java.awt.Color(102, 153, 255));
        manageProfile.setFont(getFont());
        manageProfile.setForeground(new java.awt.Color(255, 255, 255));
        manageProfile.setText("Manage Profile");
        manageProfile.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        manageProfile.setMaximumSize(new java.awt.Dimension(200, 40));
        manageProfile.setMinimumSize(new java.awt.Dimension(20, 20));
        manageProfile.setOpaque(true);
        manageProfile.setPreferredSize(new java.awt.Dimension(240, 25));
        manageProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageProfileActionPerformed(evt);
            }
        });

        reviewOrders.setBackground(new java.awt.Color(102, 153, 255));
        reviewOrders.setFont(getFont());
        reviewOrders.setForeground(new java.awt.Color(255, 255, 255));
        reviewOrders.setText("Review Order Status History");
        reviewOrders.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        reviewOrders.setMaximumSize(new java.awt.Dimension(200, 40));
        reviewOrders.setMinimumSize(new java.awt.Dimension(20, 20));
        reviewOrders.setOpaque(true);
        reviewOrders.setPreferredSize(new java.awt.Dimension(240, 25));
        reviewOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reviewOrdersActionPerformed(evt);
            }
        });

        viewCommission.setBackground(new java.awt.Color(102, 153, 255));
        viewCommission.setFont(getFont());
        viewCommission.setForeground(new java.awt.Color(255, 255, 255));
        viewCommission.setText("Review Comission");
        viewCommission.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        viewCommission.setMaximumSize(new java.awt.Dimension(200, 40));
        viewCommission.setMinimumSize(new java.awt.Dimension(20, 20));
        viewCommission.setOpaque(true);
        viewCommission.setPreferredSize(new java.awt.Dimension(240, 25));
        viewCommission.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewCommissionActionPerformed(evt);
            }
        });

        performanceReports.setBackground(new java.awt.Color(102, 153, 255));
        performanceReports.setFont(getFont());
        performanceReports.setForeground(new java.awt.Color(255, 255, 255));
        performanceReports.setText("Performance Reports");
        performanceReports.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        performanceReports.setMaximumSize(new java.awt.Dimension(200, 40));
        performanceReports.setMinimumSize(new java.awt.Dimension(20, 20));
        performanceReports.setOpaque(true);
        performanceReports.setPreferredSize(new java.awt.Dimension(240, 25));
        performanceReports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                performanceReportsActionPerformed(evt);
            }
        });

        jLabel1.setText("Customer");

        Title.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        Title.setText("Sales");

        btnLogout.setBackground(new java.awt.Color(102, 153, 255));
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setText("Logout");
        btnLogout.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnLogout.setMaximumSize(new java.awt.Dimension(200, 40));
        btnLogout.setMinimumSize(new java.awt.Dimension(20, 20));
        btnLogout.setOpaque(true);
        btnLogout.setPreferredSize(new java.awt.Dimension(240, 25));
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                            .addComponent(customerNameTextField)
                            .addComponent(serveCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                            .addComponent(manageProfile, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE))
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(performanceReports, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(reviewOrders, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(69, 69, 69)
                        .addComponent(viewCommission, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(370, 370, 370)
                        .addComponent(Title)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(399, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Title)
                    .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(customerNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(serveCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reviewOrders, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewCommission, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(manageProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(performanceReports, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(172, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void serveCustomerIdentifyResourceAssetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serveCustomerIdentifyResourceAssetsActionPerformed

        String customername = customerNameTextField.getText().trim();
        if (customername.isEmpty()) {
            return;
        }

        CustomerProfile selectedcustomer = null;
        for (CustomerProfile cp : business.getCustomerDirectory().getCustomerList()) {
            if (cp.getPerson().getName().equalsIgnoreCase(customername)) {
                selectedcustomer = cp;
                break;
            }
        }

        if (selectedcustomer == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Customer not found");
            return;
        }

        ProcessOrderJPanel aos = new ProcessOrderJPanel(business, selectedcustomer, salesperson, CardSequencePanel);
        CardSequencePanel.add("ProcessOrder", aos);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);

    }//GEN-LAST:event_serveCustomerIdentifyResourceAssetsActionPerformed

    private void manageProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageProfileActionPerformed
        // TODO add your handling code here:

//        ManageVulns aos = new  ManageVulns(businessunit, CardSequencePanel);
        // aos.setAgenda(businessunit.getRiskManagementAgenda());
//        CardSequencePanel.add("ManageVulns", aos);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);

}//GEN-LAST:event_manageProfileActionPerformed

    private void reviewOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reviewOrdersActionPerformed
        // TODO add your handling code here:

        ManageSalesPersonOrdersJPanel iet = new ManageSalesPersonOrdersJPanel(business, CardSequencePanel);

        CardSequencePanel.add("FindResourceAsset", iet);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);

    }//GEN-LAST:event_reviewOrdersActionPerformed

    private void viewCommissionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewCommissionActionPerformed
        // TODO add your handling code here:

        CardSequencePanel.removeAll();
        //      ViewBusinessUnitRiskProfile drpd= new ViewBusinessUnitRiskProfile(businessunit, CardSequencePanel);
//        ManageHazards drpd = new ManageHazards(businessunit, CardSequencePanel);
//        CardSequencePanel.add("ManageRiskProfiles", drpd);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
}//GEN-LAST:event_viewCommissionActionPerformed

    private void performanceReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_performanceReportsActionPerformed
        // TODO add your handling code here:

        CardSequencePanel.removeAll();
//        ManageIncidents aos = new  ManageIncidents(businessunit, CardSequencePanel);
        // aos.setAgenda(businessunit.getRiskManagementAgenda());
//        CardSequencePanel.add("RiskAgendaObjectives", aos);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
}//GEN-LAST:event_performanceReportsActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogoutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Title;
    private javax.swing.JButton btnLogout;
    private javax.swing.JTextField customerNameTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton manageProfile;
    private javax.swing.JButton performanceReports;
    private javax.swing.JButton reviewOrders;
    private javax.swing.JButton serveCustomer;
    private javax.swing.JButton viewCommission;
    // End of variables declaration//GEN-END:variables

}
