package UserInterface.PricingManagement;

import TheBusiness.Business.Business;
import TheBusiness.ProductManagement.Product;
import TheBusiness.Supplier.Supplier;

import javax.swing.*;
import java.awt.*;

public class AdjustTargetPricePanel extends javax.swing.JPanel {

    private Business business;
    private JPanel mainWorkArea;

    public AdjustTargetPricePanel(Business business, JPanel mainWorkArea) {
        this.business = business;
        this.mainWorkArea = mainWorkArea;
        initComponents();
        initializeSupplierCombo();
        initializeListeners();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmdsupplier = new javax.swing.JComboBox<>();
        cmdproduct = new javax.swing.JComboBox<>();
        lblsupplier = new javax.swing.JLabel();
        lblproduct = new javax.swing.JLabel();
        lblfloorprice = new javax.swing.JLabel();
        lbltargetprice = new javax.swing.JLabel();
        lblnewtargetprice = new javax.swing.JLabel();
        txtfloorPrice = new javax.swing.JTextField();
        txttargetPrice = new javax.swing.JTextField();
        txtnewTargetPrice = new javax.swing.JTextField();
        btnupdate = new javax.swing.JButton();
        btnback = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(233, 233, 233));

        lblsupplier.setText("Supplier");

        lblproduct.setText("Product");

        lblfloorprice.setText("Floor Price");

        lbltargetprice.setText("Target price");

        lblnewtargetprice.setText("New target price");

        txtfloorPrice.setEditable(false);

        txttargetPrice.setEditable(false);
        txttargetPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttargetPriceActionPerformed(evt);
            }
        });

        btnupdate.setText("Update target price");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });

        btnback.setText("back");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Helvetica", 1, 18)); // NOI18N
        jLabel2.setText("Adjust Target Price");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(btnback)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblnewtargetprice)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblproduct)
                                .addComponent(lblsupplier))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbltargetprice)
                                    .addComponent(lblfloorprice))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmdsupplier, 0, 135, Short.MAX_VALUE)
                            .addComponent(cmdproduct, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtfloorPrice)
                            .addComponent(txttargetPrice)
                            .addComponent(txtnewTargetPrice))
                        .addGap(100, 100, 100))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(btnupdate)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(btnback))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblnewtargetprice)
                        .addComponent(txtnewTargetPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmdsupplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblsupplier))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmdproduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblproduct))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtfloorPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblfloorprice))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txttargetPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbltargetprice))
                        .addGap(41, 41, 41)))
                .addGap(59, 59, 59)
                .addComponent(btnupdate)
                .addContainerGap(147, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        try {
            String supplierName = (String) cmdsupplier.getSelectedItem();
            String productName = (String) cmdproduct.getSelectedItem();

            Supplier s = business.getSupplierDirectory().findSupplierByName(supplierName);
            Product p = s.getProductCatalog().findProductByName(productName);

            double newPrice = Double.parseDouble(txtnewTargetPrice.getText());

            if (newPrice < p.getFloorPrice()) {
                JOptionPane.showMessageDialog(this, "Cannot set below FLOOR price!");
                return;
            }
            if (newPrice > p.getCeilingPrice()) {
                JOptionPane.showMessageDialog(this, "Cannot set above CEILING price!");
                return;
            }

            p.setTargetPrice(newPrice);
            txttargetPrice.setText(String.valueOf(newPrice));

            JOptionPane.showMessageDialog(this, "Target price updated!");
            txtnewTargetPrice.setText("");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Invalid Input");
        }
    }//GEN-LAST:event_btnupdateActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        CardLayout layout = (CardLayout) mainWorkArea.getLayout();
        layout.show(mainWorkArea, PricingManagerWorkAreaPanel.CARD_NAME);
    }//GEN-LAST:event_btnbackActionPerformed

    private void txttargetPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttargetPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttargetPriceActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnback;
    private javax.swing.JButton btnupdate;
    private javax.swing.JComboBox<String> cmdproduct;
    private javax.swing.JComboBox<String> cmdsupplier;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblfloorprice;
    private javax.swing.JLabel lblnewtargetprice;
    private javax.swing.JLabel lblproduct;
    private javax.swing.JLabel lblsupplier;
    private javax.swing.JLabel lbltargetprice;
    private javax.swing.JTextField txtfloorPrice;
    private javax.swing.JTextField txtnewTargetPrice;
    private javax.swing.JTextField txttargetPrice;
    // End of variables declaration//GEN-END:variables

    private void initializeSupplierCombo() {
        cmdsupplier.removeAllItems();

        for (Supplier s : business.getSupplierDirectory().getSupplierList()) {
            cmdsupplier.addItem(s.getSupplierName());
        }

        // If we have at least one supplier, pre-select and load products
        if (cmdsupplier.getItemCount() > 0) {
            cmdsupplier.setSelectedIndex(0);
            loadProductsForSelectedSupplier();
        }
    }

    private void initializeListeners() {
        cmdsupplier.addActionListener(e -> {
            loadProductsForSelectedSupplier();
            clearPriceFields();
        });

        cmdproduct.addActionListener(e -> {
            loadPriceForSelectedProduct();
        });
    }

    private void loadProductsForSelectedSupplier() {
        cmdproduct.removeAllItems();

        String supplierName = (String) cmdsupplier.getSelectedItem();
        if (supplierName == null || supplierName.trim().isEmpty()) {
            return;
        }

        Supplier sup = business.getSupplierDirectory().findSupplierByName(supplierName);
        if (sup == null) {
            return;
        }

        for (Product p : sup.getProductCatalog().getProductList()) {
            cmdproduct.addItem(p.getName());
        }

        // If at least one product exists, show its price details
        if (cmdproduct.getItemCount() > 0) {
            cmdproduct.setSelectedIndex(0);
            loadPriceForSelectedProduct();
        }
    }

    private void clearPriceFields() {
        txtfloorPrice.setText("");
        txttargetPrice.setText("");
        txtnewTargetPrice.setText("");
    }

    private void loadPriceForSelectedProduct() {
        String supplierName = (String) cmdsupplier.getSelectedItem();
        String productName = (String) cmdproduct.getSelectedItem();

        if (supplierName == null || productName == null) {
            clearPriceFields();
            return;
        }

        Supplier sup = business.getSupplierDirectory().findSupplierByName(supplierName);
        if (sup == null) {
            clearPriceFields();
            return;
        }

        Product p = sup.getProductCatalog().findProductByName(productName);
        if (p == null) {
            clearPriceFields();
            return;
        }

        txtfloorPrice.setText(String.valueOf(p.getFloorPrice()));
        txttargetPrice.setText(String.valueOf(p.getTargetPrice()));
        txtnewTargetPrice.setText(""); // user will input a new target    }
    }
}
