package UserInterface.PricingManagement;

import TheBusiness.Business.Business;
import TheBusiness.OrderManagement.MasterOrderList;
import TheBusiness.OrderManagement.Order;
import TheBusiness.OrderManagement.OrderItem;
import TheBusiness.ProductManagement.Product;
import TheBusiness.Supplier.Supplier;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

public class FinalReportPanel extends javax.swing.JPanel {

    private Business business;
    private JPanel mainWorkArea;

    public FinalReportPanel(Business business, JPanel mainWorkArea) {
        this.business = business;
        this.mainWorkArea = mainWorkArea;
        initComponents();
        loadReport();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblfinalreport = new javax.swing.JTable();
        btnexport = new javax.swing.JButton();
        btnback = new javax.swing.JButton();

        tblfinalreport.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Supplier ", "Product", "Floor Price", "Old Target Price", "New Target Price ", "Ceiling Price", "Units Sold", "Total Revenue ", "Below Target Count", "Above Target Count", "Profit Margin (Old)", "Profit Margin (New)", "Change (%)"
            }
        ));
        jScrollPane1.setViewportView(tblfinalreport);

        btnexport.setText("Export to CSV");
        btnexport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexportActionPerformed(evt);
            }
        });

        btnback.setText("<<< Back");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnback)
                        .addGap(341, 341, 341)
                        .addComponent(btnexport, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 857, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnback)
                    .addComponent(btnexport))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(130, 130, 130))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void loadReport() {
        DefaultTableModel model = (DefaultTableModel) tblfinalreport.getModel();
        model.setRowCount(0);

        MasterOrderList mol = business.getMasterOrderList();
        if (mol == null || mol.getOrders() == null || mol.getOrders().isEmpty()) {
            return; // no data
        }

        for (Supplier s : business.getSupplierDirectory().getSupplierList()) {
            for (Product p : s.getProductCatalog().getProductList()) {

                double floor = p.getFloorPrice();
                double ceiling = p.getCeilingPrice();
                double oldTarget = p.getOldTargetPrice();   // from Product
                double newTarget = p.getTargetPrice();      // current target

                int unitsSold = 0;
                double totalRevenue = 0.0;
                int belowTargetCount = 0;
                int aboveTargetCount = 0;
                double oldMarginTotal = 0.0;
                double newMarginTotal = 0.0;

                // Go through ALL orders and order items to collect stats for this product
                for (Order o : mol.getOrders()) {
                    if (o.getOrderItems() == null) {
                        continue;
                    }

                    for (OrderItem item : o.getOrderItems()) {
                        if (item == null || item.getProduct() != p) {
                            continue;
                        }

                        int qty = item.getQuantity();
                        double actualPrice = item.getActualPrice();

                        unitsSold += qty;
                        totalRevenue += qty * actualPrice;

                        // below / above target counts based on OLD target price
                        if (actualPrice < oldTarget) {
                            belowTargetCount++;
                        } else if (actualPrice > oldTarget) {
                            aboveTargetCount++;
                        }

                        // old margin based on actual price
                        oldMarginTotal += (actualPrice - floor) * qty;

                        // new margin as if we sell at NEW target (clamped between floor & ceiling)
                        double simulatedPrice = newTarget;
                        if (simulatedPrice < floor) {
                            simulatedPrice = floor;
                        } else if (simulatedPrice > ceiling) {
                            simulatedPrice = ceiling;
                        }

                        newMarginTotal += (simulatedPrice - floor) * qty;
                    }
                }

                // Convert margin totals to margin % of revenue (guard against divide by zero)
                double oldMarginPct = (totalRevenue == 0) ? 0.0 : (oldMarginTotal / totalRevenue) * 100.0;
                double newMarginPct = (totalRevenue == 0) ? 0.0 : (newMarginTotal / totalRevenue) * 100.0;
                double changePct;

                if (oldMarginPct == 0) {
                    changePct = 0.0;
                } else {
                    changePct = ((newMarginPct - oldMarginPct) / Math.abs(oldMarginPct)) * 100.0;
                }

                model.addRow(new Object[]{
                    s.getSupplierName(), // Supplier
                    p.getName(), // Product
                    floor, // Floor Price
                    oldTarget, // Old Target Price
                    newTarget, // New Target Price
                    ceiling, // Ceiling Price
                    unitsSold, // Units Sold
                    totalRevenue, // Total Revenue
                    belowTargetCount, // Below Target Count
                    aboveTargetCount, // Above Target Count
                    String.format("%.2f", oldMarginPct), // Profit Margin (Old) %
                    String.format("%.2f", newMarginPct), // Profit Margin (New) %
                    String.format("%.2f", changePct) // Change (%)
                });
            }
        }
    }


    private void btnexportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexportActionPerformed
        try {
            DefaultTableModel model = (DefaultTableModel) tblfinalreport.getModel();

            // If table is empty, try to load it once
            if (model.getRowCount() == 0) {
                loadReport();
            }
            if (model.getRowCount() == 0) {
                JOptionPane.showMessageDialog(
                        this,
                        "No data to export. Please run/load the report first.",
                        "Export",
                        JOptionPane.INFORMATION_MESSAGE
                );
                return;
            }

            // Let user choose where to save
            javax.swing.JFileChooser chooser = new javax.swing.JFileChooser();
            chooser.setDialogTitle("Save Final Pricing Report");
            chooser.setSelectedFile(new java.io.File("FinalPricingReport.csv"));

            int choice = chooser.showSaveDialog(this);
            if (choice != javax.swing.JFileChooser.APPROVE_OPTION) {
                // user cancelled
                return;
            }

            java.io.File file = chooser.getSelectedFile();
            // Ensure .csv extension
            if (!file.getName().toLowerCase().endsWith(".csv")) {
                file = new java.io.File(file.getParentFile(), file.getName() + ".csv");
            }

            try (java.io.BufferedWriter writer
                    = new java.io.BufferedWriter(new java.io.FileWriter(file))) {

                // Write header
                for (int c = 0; c < model.getColumnCount(); c++) {
                    writer.write(escapeCsv(model.getColumnName(c)));
                    if (c < model.getColumnCount() - 1) {
                        writer.write(",");
                    }
                }
                writer.newLine();

                // Write rows
                for (int r = 0; r < model.getRowCount(); r++) {
                    for (int c = 0; c < model.getColumnCount(); c++) {
                        Object value = model.getValueAt(r, c);
                        String text = (value == null) ? "" : value.toString();
                        writer.write(escapeCsv(text));
                        if (c < model.getColumnCount() - 1) {
                            writer.write(",");
                        }
                    }
                    writer.newLine();
                }
            }

            JOptionPane.showMessageDialog(
                    this,
                    "Report exported successfully:\n" + file.getAbsolutePath(),
                    "Export",
                    JOptionPane.INFORMATION_MESSAGE
            );

        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                    this,
                    "Export error: " + e.getMessage(),
                    "Export Error",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_btnexportActionPerformed

    /**
     * Simple CSV escaping: wrap values containing comma, quote or newline in
     * quotes, and escape internal quotes.
     */
    private String escapeCsv(String value) {
        if (value == null) {
            return "";
        }
        boolean needQuotes = value.contains(",") || value.contains("\"") || value.contains("\n");
        if (needQuotes) {
            value = value.replace("\"", "\"\""); // escape quotes
            return "\"" + value + "\"";
        }
        return value;
    }

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        CardLayout layout = (CardLayout) mainWorkArea.getLayout();
        layout.show(mainWorkArea, PricingManagerWorkAreaPanel.CARD_NAME);
    }//GEN-LAST:event_btnbackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnback;
    private javax.swing.JButton btnexport;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblfinalreport;
    // End of variables declaration//GEN-END:variables

}
