package UserInterface.PricingManagement;

import TheBusiness.Business.Business;
import TheBusiness.OrderManagement.MasterOrderList;
import TheBusiness.OrderManagement.Order;
import TheBusiness.OrderManagement.OrderItem;
import TheBusiness.ProductManagement.Product;

import java.awt.CardLayout;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

public class RunSimulationPanel extends javax.swing.JPanel {

    private Business business;
    private JPanel mainWorkArea;

    // formatter for nice currency-style values
    private final DecimalFormat df = new DecimalFormat("#,##0.00");

    public RunSimulationPanel(Business business, JPanel mainWorkArea) {
        this.business = business;
        this.mainWorkArea = mainWorkArea;
        initComponents();
    }

    // DO NOT USE — required by NetBeans template but never called
    RunSimulationPanel() {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbloldRevenue = new javax.swing.JLabel();
        lbloldMargin = new javax.swing.JLabel();
        lblnewRevenue = new javax.swing.JLabel();
        lblnewMargin = new javax.swing.JLabel();
        txtoldRevenue = new javax.swing.JTextField();
        txtoldMargin = new javax.swing.JTextField();
        txtnewRevenue = new javax.swing.JTextField();
        txtnewMargin = new javax.swing.JTextField();
        btnsimulation = new javax.swing.JButton();
        btnback = new javax.swing.JButton();

        lbloldRevenue.setText("Old Revenue:  ");

        lbloldMargin.setText("Old Margin");

        lblnewRevenue.setText("New Revenue: ");

        lblnewMargin.setText("New Margin:");

        txtoldRevenue.setEditable(false);

        txtoldMargin.setEditable(false);

        txtnewRevenue.setEditable(false);

        txtnewMargin.setEditable(false);

        btnsimulation.setText("run simulation");
        btnsimulation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimulationActionPerformed(evt);
            }
        });

        btnback.setText("back");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbloldRevenue)
                            .addComponent(lbloldMargin)
                            .addComponent(lblnewRevenue)
                            .addComponent(lblnewMargin))
                        .addGap(92, 92, 92)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtoldRevenue, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                            .addComponent(txtoldMargin)
                            .addComponent(txtnewRevenue)
                            .addComponent(txtnewMargin)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(btnback))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addComponent(btnsimulation)))
                .addContainerGap(186, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(btnback)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbloldRevenue)
                    .addComponent(txtoldRevenue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbloldMargin)
                    .addComponent(txtoldMargin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblnewRevenue)
                    .addComponent(txtnewRevenue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblnewMargin)
                    .addComponent(txtnewMargin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(btnsimulation)
                .addContainerGap(103, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnsimulationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimulationActionPerformed
        // TODO add your handling code here:
        runSimulation();
    }//GEN-LAST:event_btnsimulationActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        CardLayout layout = (CardLayout) mainWorkArea.getLayout();
        layout.show(mainWorkArea, PricingManagerWorkAreaPanel.CARD_NAME);
    }//GEN-LAST:event_btnbackActionPerformed

    /**
     * Old Revenue = sum(actualPrice * quantity) over all order items
     *
     * Old Margin = sum((actualPrice - floorPrice) * quantity)
     *
     * New Revenue = sum(simulatedPrice * quantity), where simulatedPrice is the
     * current target price clamped between floor & ceiling
     *
     * New Margin = sum((simulatedPrice - floorPrice) * quantity)
     *
     * This uses the CURRENT target price of each product, so any updates you
     * made in AdjustTargetPricePanel will affect the "New" values.
     */
    private void runSimulation() {

        MasterOrderList mol = business.getMasterOrderList();

        double oldRevenue = 0.0;
        double oldMargin = 0.0;
        double newRevenue = 0.0;
        double newMargin = 0.0;

        if (mol == null || mol.getOrders() == null || mol.getOrders().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "No orders available to simulate.",
                    "Simulation",
                    JOptionPane.INFORMATION_MESSAGE);
            txtoldRevenue.setText("0.00");
            txtoldMargin.setText("0.00");
            txtnewRevenue.setText("0.00");
            txtnewMargin.setText("0.00");
            return;
        }

        for (Order order : mol.getOrders()) {
            if (order == null || order.getOrderItems() == null) {
                continue;
            }

            for (OrderItem item : order.getOrderItems()) {
                if (item == null || item.getProduct() == null) {
                    continue;
                }

                Product p = item.getProduct();
                int qty = item.getQuantity();
                double actualPrice = item.getActualPrice();

                double floor = p.getFloorPrice();
                double ceiling = p.getCeilingPrice();
                double target = p.getTargetPrice();

                // Old scenario: whatever was actually charged
                double itemOldRevenue = actualPrice * qty;
                double itemOldMargin = (actualPrice - floor) * qty;

                oldRevenue += itemOldRevenue;
                oldMargin += itemOldMargin;

                // New scenario: assume we now sell at target price (within floor/ceiling band)
                double simulatedPrice = target;
                if (simulatedPrice < floor) {
                    simulatedPrice = floor;
                } else if (simulatedPrice > ceiling) {
                    simulatedPrice = ceiling;
                }

                double itemNewRevenue = simulatedPrice * qty;
                double itemNewMargin = (simulatedPrice - floor) * qty;

                newRevenue += itemNewRevenue;
                newMargin += itemNewMargin;
            }
        }

        // Show nicely formatted numbers
        txtoldRevenue.setText(df.format(oldRevenue));
        txtoldMargin.setText(df.format(oldMargin));
        txtnewRevenue.setText(df.format(newRevenue));
        txtnewMargin.setText(df.format(newMargin));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnback;
    private javax.swing.JButton btnsimulation;
    private javax.swing.JLabel lblnewMargin;
    private javax.swing.JLabel lblnewRevenue;
    private javax.swing.JLabel lbloldMargin;
    private javax.swing.JLabel lbloldRevenue;
    private javax.swing.JTextField txtnewMargin;
    private javax.swing.JTextField txtnewRevenue;
    private javax.swing.JTextField txtoldMargin;
    private javax.swing.JTextField txtoldRevenue;
    // End of variables declaration//GEN-END:variables
}
